name: sbom
description: A Software Bill of Materials generator specifically for Dart packages.
version: 2.0.0
homepage: https://github.com/shamblett/sbom
repository: https://github.com/shamblett/sbom

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: '>=3.0.0 <4.0.0'

dependencies:
 path: '^1.8.3'
 meta: '^1.9.1'
 args: '^2.4.1'
 yaml: '^3.1.2'
 crypto: '^3.0.3'
 pub_cache: '^0.3.2'

executables:
 sbom:

dev_dependencies:
 dart_code_metrics: '^5.7.3'
 lints: '^2.1.0'
 test: '^1.24.2'





